@rootURL = http://localhost:3000

###
GET {{rootURL}}

###
POST {{rootURL}}/auth/register

###
POST {{rootURL}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"bii",
    "lName":"Ranabhat",
    "phone":"1234567890",
    "email":"kliimdddn@gmail.com",
    "password":"aA2@aa"
 
}

### post to activate user
POST {{rootURL}}/api/v1/auth/activate-user
Content-Type: application/json

{
   "sessionId":"23",
   "t":"e8ca1fb4-8f8e-4cca-b054-2d3c613c2bd9"
    
}


###
POST {{rootURL}}/user
Content-Type: application/json

{
    "fName":"a",
    "lName":"b",
    "phone":"1234567",
    "email":"z@gmail.com",
    "password":"as"

}

###
POST {{rootURL}}/user/login
Content-Type: application/json

{
    "email":"z@gmail.com",
    "password":"as"
}

###
GET {{rootURL}}/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzMzOTc0OTU1LCJleHAiOjE3MzQwNjEzNTV9.m0ahuhptg7s8ojVLyCjOa36quMwHWjvP_BoJ1Taotwc