@rootURL = http://localhost:3000/api/v1

###
GET {{rootURL}}

###
POST {{rootURL}}/auth/register

###
POST {{rootURL}}/user
Content-Type: application/json

{
    "fName":"a",
    "lName":"b",
    "phone":"1234567",
    "email":"z@gmail.com",
    "password":"as"

}

###
POST {{rootURL}}/user
Content-Type: application/json

{
    "fName":"a",
    "lName":"b",
    "phone":"1234567",
    "email":"z@gmail.com",
    "password":"as"

}

###
POST {{rootURL}}/user/login
Content-Type: application/json

{
    "email":"z@gmail.com",
    "password":"as"
}

###
GET {{rootURL}}/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzMzOTc0OTU1LCJleHAiOjE3MzQwNjEzNTV9.m0ahuhptg7s8ojVLyCjOa36quMwHWjvP_BoJ1Taotwc