import mongoose from "mongoose";

const books = [
  {
    status: "active",
    slug: "artificial-intelligence-a-modern-approach",
    title: "Artificial Intelligence: A Modern Approach",
    year: 2020,
    author: "Stuart Russell & Peter Norvig",
    imgUrl: "https://images-na.ssl-images-amazon.com/images/I/81D1U9cQ0IL.jpg",
    imageList: [],
    isbn: "9780134610993",
    genre: "AI",
    available: true,
    averageRating: 4.8,
    description:
      "Comprehensive AI textbook covering problem-solving, knowledge representation, and learning.",
    expectedAvailable: null,
    addedBy: { name: "Admin One", adminId: new mongoose.Types.ObjectId() },
    lastUpdatedBy: {
      name: "Admin One",
      adminId: new mongoose.Types.ObjectId(),
    },
  },
  {
    status: "active",
    slug: "hands-on-machine-learning",
    title: "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow",
    year: 2022,
    author: "Aurélien Géron",
    imgUrl: "https://images-na.ssl-images-amazon.com/images/I/81dQwQlmAXL.jpg",
    imageList: [],
    isbn: "9781098125974",
    genre: "Machine Learning",
    available: false,
    averageRating: 4.7,
    description:
      "Practical guide to building ML models using Python libraries.",
    expectedAvailable: new Date("2025-05-05"),
    addedBy: { name: "Admin Two", adminId: new mongoose.Types.ObjectId() },
    lastUpdatedBy: {
      name: "Admin Two",
      adminId: new mongoose.Types.ObjectId(),
    },
  },
  {
    status: "active",
    slug: "deep-learning-goodfellow",
    title: "Deep Learning",
    year: 2016,
    author: "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
    imgUrl: "https://images-na.ssl-images-amazon.com/images/I/61MvF2F1oAL.jpg",
    imageList: [],
    isbn: "9780262035613",
    genre: "AI",
    available: true,
    averageRating: 4.6,
    description:
      "Foundational deep learning book covering theory, applications, and algorithms.",
    expectedAvailable: null,
    addedBy: { name: "Admin Three", adminId: new mongoose.Types.ObjectId() },
    lastUpdatedBy: {
      name: "Admin Three",
      adminId: new mongoose.Types.ObjectId(),
    },
  },
  {
    status: "active",
    slug: "clean-code",
    title: "Clean Code: A Handbook of Agile Software Craftsmanship",
    year: 2008,
    author: "Robert C. Martin",
    imgUrl: "https://images-na.ssl-images-amazon.com/images/I/41SH-SvWPxL.jpg",
    imageList: [],
    isbn: "9780132350884",
    genre: "Software Engineering",
    available: true,
    averageRating: 4.8,
    description: "Guidelines and principles for writing clean, readable code.",
    expectedAvailable: null,
    addedBy: { name: "Admin One", adminId: new mongoose.Types.ObjectId() },
    lastUpdatedBy: {
      name: "Admin Four",
      adminId: new mongoose.Types.ObjectId(),
    },
  },
  {
    status: "active",
    slug: "design-patterns",
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    year: 1994,
    author: "Erich Gamma et al.",
    imgUrl: "https://images-na.ssl-images-amazon.com/images/I/81gtKoapHFL.jpg",
    imageList: [],
    isbn: "9780201633610",
    genre: "Software Design",
    available: false,
    averageRating: 4.5,
    description: "Classic book on reusable object-oriented design patterns.",
    expectedAvailable: new Date("2025-04-30"),
    addedBy: { name: "Admin Two", adminId: new mongoose.Types.ObjectId() },
    lastUpdatedBy: {
      name: "Admin Two",
      adminId: new mongoose.Types.ObjectId(),
    },
  },
  {
    status: "inactive",
    slug: "you-dont-know-js",
    title: "You Don’t Know JS Yet",
    year: 2020,
    author: "Kyle Simpson",
    imgUrl: "https://images-na.ssl-images-amazon.com/images/I/71lJxQSdPTL.jpg",
    imageList: [],
    isbn: "9781098124045",
    genre: "JavaScript",
    available: true,
    averageRating: 4.6,
    description: "In-depth exploration of the JavaScript language.",
    expectedAvailable: null,
    addedBy: { name: "Admin Three", adminId: new mongoose.Types.ObjectId() },
    lastUpdatedBy: {
      name: "Admin One",
      adminId: new mongoose.Types.ObjectId(),
    },
  },
  {
    status: "active",
    slug: "refactoring",
    title: "Refactoring: Improving the Design of Existing Code",
    year: 2018,
    author: "Martin Fowler",
    imgUrl: "https://images-na.ssl-images-amazon.com/images/I/51kzOGJc2fL.jpg",
    imageList: [],
    isbn: "9780134757599",
    genre: "Software Engineering",
    available: false,
    averageRating: 4.4,
    description:
      "Techniques to improve code structure without changing behavior.",
    expectedAvailable: new Date("2025-05-20"),
    addedBy: { name: "Admin Two", adminId: new mongoose.Types.ObjectId() },
    lastUpdatedBy: {
      name: "Admin Four",
      adminId: new mongoose.Types.ObjectId(),
    },
  },
  {
    status: "active",
    slug: "grokking-algorithms",
    title: "Grokking Algorithms",
    year: 2016,
    author: "Aditya Bhargava",
    imgUrl: "https://images-na.ssl-images-amazon.com/images/I/91asIC1fRwL.jpg",
    imageList: [],
    isbn: "9781617292231",
    genre: "Algorithms",
    available: true,
    averageRating: 4.7,
    description:
      "Beginner-friendly guide to algorithms using illustrations and examples.",
    expectedAvailable: null,
    addedBy: { name: "Admin One", adminId: new mongoose.Types.ObjectId() },
    lastUpdatedBy: {
      name: "Admin Two",
      adminId: new mongoose.Types.ObjectId(),
    },
  },
  {
    status: "active",
    slug: "introduction-to-algorithms",
    title: "Introduction to Algorithms",
    year: 2009,
    author: "Thomas H. Cormen et al.",
    imgUrl: "https://images-na.ssl-images-amazon.com/images/I/81wgc5I5lUL.jpg",
    imageList: [],
    isbn: "9780262033848",
    genre: "Algorithms",
    available: true,
    averageRating: 4.5,
    description:
      "Comprehensive textbook on algorithms, widely used in academics.",
    expectedAvailable: null,
    addedBy: { name: "Admin Three", adminId: new mongoose.Types.ObjectId() },
    lastUpdatedBy: {
      name: "Admin Three",
      adminId: new mongoose.Types.ObjectId(),
    },
  },
  {
    status: "inactive",
    slug: "python-crash-course",
    title: "Python Crash Course",
    year: 2019,
    author: "Eric Matthes",
    imgUrl: "https://images-na.ssl-images-amazon.com/images/I/81eR5Zt1NML.jpg",
    imageList: [],
    isbn: "9781593279288",
    genre: "Programming",
    available: false,
    averageRating: 4.7,
    description:
      "Hands-on project-based introduction to programming with Python.",
    expectedAvailable: new Date("2025-06-01"),
    addedBy: { name: "Admin One", adminId: new mongoose.Types.ObjectId() },
    lastUpdatedBy: {
      name: "Admin Two",
      adminId: new mongoose.Types.ObjectId(),
    },
  },
];

export default books;
